/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor.vista;

import gestor.patrones.PrincipalVisitador;
import java.awt.CardLayout;

/**
 *
 * @author Usuario
 */
public class FrmGestor extends javax.swing.JFrame implements PrincipalVisitador {

    /**
     * Creates new form FrmGestor
     */
    public FrmGestor() {
        initComponents();
        
       pnlInicioSesion.setVisitador(this);
       pnlHome.setVisitador(this);
       pnlProyecto.setVisitador(this);
       pnlTarea.setVisitador(this);
       pnlTareaSuspendida.setVisitador(this);
       pnlRazonSuspensionProyecto.setVisitador(this);
       pnlRazonSuspensionTarea.setVisitador(this);
       pnlCrearProyecto.setVisitador(this);
       pnlAñadirParticipanteProyecto.setVisitador(this);
       pnlAñadirParticipanteTarea.setVisitador(this);
       pnlTareaProyecto.setVisitador(this);
       pnlCrearTareaProyecto.setVisitador(this);
       pnlAñadirParticipanteCrearTarea.setVisitador(this);
       pnlAñadirParticipanteTareaProyecto.setVisitador(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlTarjetas = new javax.swing.JPanel();
        pnlInicioSesion = new gestor.vista.PnlInicioSesion();
        pnlHome = new gestor.vista.PnlHome();
        pnlProyecto = new gestor.vista.PnlProyecto();
        pnlTarea = new gestor.vista.PnlTarea();
        pnlTareaSuspendida = new gestor.vista.PnlTareaSuspendida();
        pnlCrearProyecto = new gestor.vista.PnlCrearProyecto();
        pnlAñadirParticipanteProyecto = new gestor.vista.PnlAñadirParticipanteProyecto();
        pnlAñadirParticipanteTarea = new gestor.vista.PnlAñadirParticipanteTarea();
        pnlTareaProyecto = new gestor.vista.PnlTareaProyecto();
        pnlCrearTareaProyecto = new gestor.vista.PnlCrearTareaProyecto();
        pnlRazonSuspensionProyecto = new gestor.vista.PnlRazonSuspensionProyecto();
        pnlRazonSuspensionTarea = new gestor.vista.PnlRazonSuspensionTarea();
        pnlAñadirParticipanteCrearTarea = new gestor.vista.PnlAñadirParticipanteCrearTarea();
        pnlAñadirParticipanteTareaProyecto = new gestor.vista.PnlAñadirParticipanteTareaProyecto();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor de proyectos");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        PnlTarjetas.setLayout(new java.awt.CardLayout());
        PnlTarjetas.add(pnlInicioSesion, "tarjetaInicioSesion");
        PnlTarjetas.add(pnlHome, "tarjetaHome");
        PnlTarjetas.add(pnlProyecto, "tarjetaProyecto");
        PnlTarjetas.add(pnlTarea, "tarjetaTarea");
        PnlTarjetas.add(pnlTareaSuspendida, "tarjetaTareaSuspendida");
        PnlTarjetas.add(pnlCrearProyecto, "tarjetaCrearProyecto");
        PnlTarjetas.add(pnlAñadirParticipanteProyecto, "tarjetaAñadirParticipanteProyecto");
        PnlTarjetas.add(pnlAñadirParticipanteTarea, "tarjetaAñadirParticipanteTarea");
        PnlTarjetas.add(pnlTareaProyecto, "tarjetaTareaProyecto");
        PnlTarjetas.add(pnlCrearTareaProyecto, "tarjetaCrearTareaProyecto");
        PnlTarjetas.add(pnlRazonSuspensionProyecto, "tarjetaRazonSuspensionProyecto");
        PnlTarjetas.add(pnlRazonSuspensionTarea, "tarjetaRazonSuspensionTarea");
        PnlTarjetas.add(pnlAñadirParticipanteCrearTarea, "tarjetaAñadirParticipanteCrearTarea");
        PnlTarjetas.add(pnlAñadirParticipanteTareaProyecto, "tarjetaAñadirParticipanteTareaProyecto");

        jPanel3.add(PnlTarjetas, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestor().setVisible(true);
            }
        });
    }
    
    @Override
    public void cambiarTarjeta(String tarjeta) {
        ((CardLayout) PnlTarjetas.getLayout()).show(PnlTarjetas, tarjeta);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlTarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private gestor.vista.PnlAñadirParticipanteCrearTarea pnlAñadirParticipanteCrearTarea;
    private gestor.vista.PnlAñadirParticipanteProyecto pnlAñadirParticipanteProyecto;
    private gestor.vista.PnlAñadirParticipanteTarea pnlAñadirParticipanteTarea;
    private gestor.vista.PnlAñadirParticipanteTareaProyecto pnlAñadirParticipanteTareaProyecto;
    private gestor.vista.PnlCrearProyecto pnlCrearProyecto;
    private gestor.vista.PnlCrearTareaProyecto pnlCrearTareaProyecto;
    private gestor.vista.PnlHome pnlHome;
    private gestor.vista.PnlInicioSesion pnlInicioSesion;
    private gestor.vista.PnlProyecto pnlProyecto;
    private gestor.vista.PnlRazonSuspensionProyecto pnlRazonSuspensionProyecto;
    private gestor.vista.PnlRazonSuspensionTarea pnlRazonSuspensionTarea;
    private gestor.vista.PnlTarea pnlTarea;
    private gestor.vista.PnlTareaProyecto pnlTareaProyecto;
    private gestor.vista.PnlTareaSuspendida pnlTareaSuspendida;
    // End of variables declaration//GEN-END:variables
}
